name: Deploy App

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          # Sync backend
          rsync -avz --delete --exclude '.git*' --exclude 'node_modules' ./backend/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/backend/

          # Sync frontend (Next.js)
          rsync -avz --delete --exclude '.git*' --exclude 'node_modules' ./frontend/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/frontend/

          # Run deploy commands via SSH
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Load NVM and Bun
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export BUN_INSTALL="$HOME/.bun"
            export PATH="$BUN_INSTALL/bin:$PATH:$HOME/.npm-global/bin:$PATH"

            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}
            export AWS_SECRET_STORAGE_NAME=growthify-secrets

            # === Backend ===
            cd ~/backend
            echo "${{ secrets.BACKEND_ENV_FILE }}" > .env
            bun install
            pm2 delete backend || true
            pm2 start "bun run src/index.ts" --name backend

            # === Frontend (Next.js) ===
            cd ~/frontend
            echo "${{ secrets.FRONTEND_ENV_FILE }}" > .env
            bun install
            bun run build
            pm2 delete frontend || true
            pm2 start "bun run start" --name frontend

            # Persist PM2 apps across reboots
            pm2 save

            # Reload Caddy to reflect any config changes
            sudo systemctl reload caddy
          EOF

      - name: Clean up SSH key
        run: rm -f ~/.ssh/id_rsa
